development:
  adapter: mysql2
  encoding: utf8
  database: cms
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: cms_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: cms_production
  pool: 5
  username: root
  password: 